if(NOT DK_BUILD_MEMORY)
    message(FATAL_ERROR "DK_BUILD_PLATFORM requires DK_BUILD_MEMORY")
endif()
set(CMAKE_FOLDER "Engine/Platform")
find_package(SDL3 CONFIG REQUIRED)
add_library(dk_platform STATIC src/Window.cpp)
add_library(dk::platform ALIAS dk_platform)
target_sources(dk_platform PUBLIC FILE_SET HEADERS BASE_DIRS include FILES include/dk/platform/Window.hpp)
target_link_libraries(dk_platform PUBLIC dk::core dk::memory PRIVATE SDL3::SDL3)
dk_target_defaults(dk_platform)
