# Preserve a unique test directory for inspection, never reuse/overwrite real products.
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef suffix)
set(root "${WORK_DIR}/assetc-${suffix}/工程 😀")
file(MAKE_DIRECTORY "${root}/资产")
file(COPY "${FIXTURES}/triangle.bin" "${FIXTURES}/rgba.png" DESTINATION "${root}/资产")
file(COPY_FILE "${FIXTURES}/triangle.gltf" "${root}/资产/模型.gltf")
file(COPY_FILE "${FIXTURES}/triangle.glb" "${root}/资产/模型.glb")
file(WRITE "${root}/project.dkproj" "unrelated project bytes")
function(invoke expected)
    execute_process(COMMAND "${ASSETC}" ${ARGN}
        RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE error ENCODING UTF-8)
    if(NOT code STREQUAL "${expected}")
        message(FATAL_ERROR "assetc expected ${expected}, got ${code}: ${error} ${output}")
    endif()
    if(NOT expected EQUAL 0)
        if(NOT output STREQUAL "" OR error STREQUAL "")
            message(FATAL_ERROR "Failure must use stderr only: ${output} ${error}")
        endif()
    endif()
    set(output "${output}" PARENT_SCOPE)
endfunction()
invoke(0 import --project-root "${root}" --source "资产/模型.gltf" --output "产物 一" --unit-scale 2)
string(JSON format GET "${output}" format)
string(JSON id GET "${output}" root_id)
string(JSON count LENGTH "${output}" outputs)
if(NOT format STREQUAL "DeckerAssetCompileResult" OR NOT count EQUAL 3)
    message(FATAL_ERROR "Invalid success JSON: ${output}")
endif()
file(READ "${root}/资产/模型.gltf.meta" meta)
string(JSON saved_id GET "${meta}" root_id)
file(READ "${root}/产物 一/manifest.json" manifest)
string(JSON scale GET "${manifest}" meta settings unit_scale)
string(JSON textures LENGTH "${manifest}" textures)
string(JSON inputs LENGTH "${manifest}" inputs)
if(NOT saved_id STREQUAL id OR NOT scale EQUAL 2 OR NOT textures EQUAL 1 OR NOT inputs EQUAL 3)
    message(FATAL_ERROR "Incorrect artifact/meta contents")
endif()
file(SHA256 "${root}/产物 一/data.bin" original_data)
invoke(0 import --project-root "${root}" --source "资产/模型.gltf" --output "产物 二")
string(JSON second_id GET "${output}" root_id)
file(READ "${root}/资产/模型.gltf.meta" second_meta)
file(SHA256 "${root}/产物 二/data.bin" second_data)
if(NOT second_id STREQUAL id OR NOT second_meta STREQUAL meta OR NOT second_data STREQUAL original_data)
    message(FATAL_ERROR "Reimport changed identities, default scale, or CPU data")
endif()
invoke(0 import --project-root "${root}" --source "资产/模型.glb" --output "内嵌")
file(READ "${root}/内嵌/manifest.json" embedded)
string(JSON embedded_inputs LENGTH "${embedded}" inputs)
string(JSON embedded_textures LENGTH "${embedded}" textures)
if(NOT embedded_inputs EQUAL 1 OR NOT embedded_textures EQUAL 1)
    message(FATAL_ERROR "GLB did not import embedded JPEG")
endif()
invoke(1 import --project-root "${root}" --source "资产/模型.gltf" --output "产物 一")
file(WRITE "${root}/资产/rgba.png" "corrupt PNG")
invoke(1 import --project-root "${root}" --source "资产/模型.gltf" --output "失败")
file(READ "${root}/资产/模型.gltf.meta" after_meta)
file(SHA256 "${root}/产物 一/data.bin" after_data)
file(READ "${root}/project.dkproj" project)
if(EXISTS "${root}/失败" OR NOT after_meta STREQUAL meta OR NOT after_data STREQUAL original_data OR NOT project STREQUAL "unrelated project bytes")
    message(FATAL_ERROR "Failed import modified committed state")
endif()
invoke(2)
invoke(2 import --project-root "${root}" --source "资产/模型.gltf" --output next --unit-scale nan)
invoke(2 import --project-root "${root}" --source "资产/模型.gltf" --output next --output duplicate)
invoke(2 import --project-root "${root}" --source "资产/模型.gltf" --output next --unknown value)
invoke(0 --help)
if(NOT output STREQUAL "")
    message(FATAL_ERROR "Help must not contaminate JSON stdout")
endif()
message(STATUS "assetc external PNG, embedded JPEG, reimport, rollback and Unicode CLI passed: ${root}")
