string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
set(root "${WORK_DIR}/${suffix}/工程")
execute_process(COMMAND "${PROBE}" "${root}" seed "${KIND}" "${POINT}" RESULT_VARIABLE seeded)
if(NOT seeded EQUAL 0)
    message(FATAL_ERROR "Seed failed: ${seeded}")
endif()
execute_process(COMMAND "${PROBE}" "${root}" crash "${KIND}" "${POINT}" RESULT_VARIABLE crashed)
if(NOT crashed EQUAL 73)
    message(FATAL_ERROR "Expected interrupted process exit 73, got ${crashed}")
endif()
execute_process(COMMAND "${PROBE}" "${root}" recover "${KIND}" "${POINT}" RESULT_VARIABLE recovered)
if(NOT recovered EQUAL 0)
    message(FATAL_ERROR "Recovery failed: ${recovered}")
endif()
file(REMOVE_RECURSE "${WORK_DIR}/${suffix}")
