string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef suffix)
set(root "${WORK_DIR}/cache-${suffix}/工程 😀")
file(MAKE_DIRECTORY "${root}/资产")
file(COPY "${FIXTURES}/triangle.bin" "${FIXTURES}/rgba.png" DESTINATION "${root}/资产")
file(COPY_FILE "${FIXTURES}/triangle.gltf" "${root}/资产/模型.gltf")
function(run)
    execute_process(COMMAND "${ASSETC}" cache --project-root "${root}" --source "资产/模型.gltf" ${ARGN}
        RESULT_VARIABLE code OUTPUT_VARIABLE text ERROR_VARIABLE error ENCODING UTF-8)
    if(NOT code STREQUAL "0")
        message(FATAL_ERROR "Cache process failed: ${code} ${error}")
    endif()
    string(JSON hit GET "${text}" cache_hit)
    string(JSON key GET "${text}" key)
    string(JSON id GET "${text}" root_id)
    string(JSON directory GET "${text}" directory)
    set(hit "${hit}" PARENT_SCOPE)
    set(key "${key}" PARENT_SCOPE)
    set(id "${id}" PARENT_SCOPE)
    set(directory "${directory}" PARENT_SCOPE)
endfunction()
run()
if(hit)
    message(FATAL_ERROR "Cold import hit cache")
endif()
set(first_key "${key}")
set(first_id "${id}")
set(first_directory "${directory}")
file(READ "${root}/资产/模型.gltf.meta" before_meta)
run()
if(NOT hit OR NOT key STREQUAL first_key OR NOT id STREQUAL first_id OR NOT directory STREQUAL first_directory)
    message(FATAL_ERROR "Separate process did not reuse cache")
endif()
file(READ "${root}/资产/模型.gltf.meta" after_meta)
if(NOT before_meta STREQUAL after_meta)
    message(FATAL_ERROR "Cache hit changed metadata")
endif()
run(--unit-scale 2)
if(hit OR key STREQUAL first_key OR NOT id STREQUAL first_id)
    message(FATAL_ERROR "Settings failed to invalidate while keeping identity")
endif()
if(NOT EXISTS "${root}/${first_directory}/data.bin")
    message(FATAL_ERROR "Rebuild deleted old cache")
endif()
run()
if(NOT hit)
    message(FATAL_ERROR "Meta settings were not retained")
endif()
