string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef run_id)
set(root "${WORK_DIR}/${run_id}/工程 📦")
set(relative "样例 数据.dkf")
set(target "${root}/${relative}")
file(MAKE_DIRECTORY "${root}")

function(run_demo expected)
    execute_process(COMMAND "${DEMO}" ${ARGN}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE diagnostics
        TIMEOUT 20 ENCODING UTF-8)
    if(NOT result STREQUAL "${expected}")
        message(FATAL_ERROR "Expected ${expected}, got ${result}: ${diagnostics}")
    endif()
    string(REPLACE "\r\n" "\n" output "${output}")
    if(NOT diagnostics MATCHES "\\[foundation-demo\\]")
        message(FATAL_ERROR "Missing diagnostic on stderr: ${diagnostics}")
    endif()
    if(NOT expected EQUAL 0 AND NOT output STREQUAL "")
        message(FATAL_ERROR "Failure polluted stdout: ${output}")
    endif()
    set(last_output "${output}" PARENT_SCOPE)
    set(last_error "${diagnostics}" PARENT_SCOPE)
endfunction()

if(CASE STREQUAL "roundtrip" OR CASE STREQUAL "overwrite")
    run_demo(0 save "${root}" "${relative}")
    set(saved "${last_output}")
    if(NOT saved MATCHES "^entity_id=[0-9a-f-]+\nworld_point=[^\n]+\nlocal_point=1 2 3\nroundtrip=ok\n$")
        message(FATAL_ERROR "Unexpected sample stdout: ${saved}")
    endif()
    run_demo(0 load "${root}" "${relative}")
    if(NOT last_output STREQUAL saved)
        message(FATAL_ERROR "Separate process reload changed identity or derived transform")
    endif()
    if(CASE STREQUAL "overwrite")
        run_demo(0 save "${root}" "${relative}")
        if(last_output STREQUAL saved)
            message(FATAL_ERROR "New sample reused old identity")
        endif()
        set(saved "${last_output}")
        run_demo(0 load "${root}" "${relative}")
        if(NOT last_output STREQUAL saved)
            message(FATAL_ERROR "Replacement did not persist the new identity")
        endif()
    endif()
elseif(CASE STREQUAL "missing_file")
    run_demo(1 load "${root}" "${relative}")
    if(NOT last_error MATCHES "not_found" OR NOT last_error MATCHES "sample.load")
        message(FATAL_ERROR "Missing error code or load context")
    endif()
elseif(CASE STREQUAL "outside_root")
    run_demo(1 save "${root}" "../outside.dkf")
    if(NOT last_error MATCHES "invalid_argument" OR EXISTS "${root}/../outside.dkf")
        message(FATAL_ERROR "Project escape was not rejected")
    endif()
elseif(CASE STREQUAL "missing_parent")
    run_demo(1 save "${root}" "missing/child.dkf")
    if(NOT last_error MATCHES "not_found" OR EXISTS "${root}/missing")
        message(FATAL_ERROR "Missing parent semantics changed")
    endif()
elseif(CASE STREQUAL "usage")
    run_demo(2)
    run_demo(2 unknown "${root}" "${relative}")
else()
    set(id "00112233-4455-4677-8899-aabbccddeeff")
    set(version 1)
    set(matrix "1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1")
    set(extra "")
    set(expected_error invalid_argument)
    if(CASE STREQUAL "invalid_id")
        set(id bad-id)
    elseif(CASE STREQUAL "nil_id")
        set(id "00000000-0000-0000-0000-000000000000")
    elseif(CASE STREQUAL "bad_version")
        set(version 99)
        set(expected_error not_supported)
    elseif(CASE STREQUAL "truncated")
        set(matrix "1 0 0")
    elseif(CASE STREQUAL "nonfinite")
        set(matrix "nan 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1")
    elseif(CASE STREQUAL "projective")
        set(matrix "1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1")
    elseif(CASE STREQUAL "singular")
        set(matrix "0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1")
        set(expected_error invalid_state)
    elseif(CASE STREQUAL "trailing")
        set(extra "garbage")
    elseif(CASE STREQUAL "oversized")
        string(REPEAT "x" 4097 extra)
    else()
        message(FATAL_ERROR "Unknown test case: ${CASE}")
    endif()
    file(WRITE "${target}" "DK_FOUNDATION_SAMPLE ${version}\nentity ${id}\nmatrix ${matrix}\n${extra}")
    file(SHA256 "${target}" before)
    run_demo(1 load "${root}" "${relative}")
    if(NOT last_error MATCHES "${expected_error}")
        message(FATAL_ERROR "Unexpected error category: ${last_error}")
    endif()
    file(SHA256 "${target}" after)
    if(NOT before STREQUAL after)
        message(FATAL_ERROR "Loading corrupt input changed its bytes")
    endif()
endif()

file(GLOB residue "${root}/.dk-save-*.tmp")
if(residue)
    message(FATAL_ERROR "Unexpected atomic-save temporary files: ${residue}")
endif()
