set(root "${WORK_DIR}/工程 空间")
file(MAKE_DIRECTORY "${root}")
set(script "${WORK_DIR}/创建 场景.luau")
configure_file("${EXAMPLE}" "${script}" COPYONLY)
execute_process(COMMAND "${RUNNER}" --project-root "${root}" --script "${script}"
    RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 20 ENCODING UTF-8)
if(NOT code EQUAL 0 OR NOT output STREQUAL "" OR NOT errors STREQUAL "")
    message(FATAL_ERROR "Luau example exit=${code}; stderr=${errors}; stdout=${output}")
endif()
file(WRITE "${WORK_DIR}/reload.jsonl" [=[
{"jsonrpc":"2.0","id":1,"method":"scene.load","params":{"manifest":"project.json"}}
{"jsonrpc":"2.0","id":2,"method":"scene.query"}
]=])
execute_process(COMMAND "${RUNNER}" --project-root "${root}" --batch "${WORK_DIR}/reload.jsonl"
    RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 20 ENCODING UTF-8)
if(NOT code EQUAL 0 OR NOT errors STREQUAL "")
    message(FATAL_ERROR "Reload failed: ${code} ${errors} ${output}")
endif()
string(STRIP "${output}" output)
string(REPLACE "\n" ";" lines "${output}")
list(GET lines -1 query)
string(JSON count GET "${query}" result value state entity_count)
string(JSON dirty GET "${query}" result value state dirty)
if(NOT count EQUAL 3 OR dirty)
    message(FATAL_ERROR "Wrong persisted Luau scene: ${query}")
endif()
set(children 0)
foreach(index RANGE 0 2)
    string(JSON name GET "${query}" result value entities ${index} name)
    string(JSON x GET "${query}" result value entities ${index} world_matrix 3)
    if(name STREQUAL "实体 1")
        set(expected 2)
    elseif(name STREQUAL "实体 2")
        set(expected 6)
    elseif(name STREQUAL "实体 3")
        set(expected 8)
    else()
        message(FATAL_ERROR "Unexpected entity name: ${name}")
    endif()
    if(NOT x EQUAL expected)
        message(FATAL_ERROR "Persisted world transform differs for ${name}: ${x}")
    endif()
endforeach()
foreach(case IN ITEMS syntax runtime extension missing mixed auto_guard)
    set(extra)
    set(bad "${WORK_DIR}/${case}.luau")
    file(WRITE "${bad}" "error('expected script failure')")
    if(case STREQUAL "syntax")
        file(WRITE "${bad}" "local =")
    elseif(case STREQUAL "extension")
        set(bad "${WORK_DIR}/external.bytecode")
        file(WRITE "${bad}" "not source")
    elseif(case STREQUAL "missing")
        set(bad "${WORK_DIR}/never-created.luau")
    elseif(case STREQUAL "mixed")
        list(APPEND extra --stdio)
    elseif(case STREQUAL "auto_guard")
        list(APPEND extra --auto-guard)
    endif()
    execute_process(COMMAND "${RUNNER}" --project-root "${root}" --script "${bad}" ${extra}
        RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 10 ENCODING UTF-8)
    if(NOT code EQUAL 2 OR NOT output STREQUAL "" OR errors STREQUAL "")
        message(FATAL_ERROR "${case}: expected error on stderr with exit 2: ${code} ${errors} ${output}")
    endif()
    if(case STREQUAL "runtime" AND NOT errors MATCHES "runtime.luau:1")
        message(FATAL_ERROR "Missing script location: ${errors}")
    endif()
endforeach()
