set(root "${WORK_DIR}/工程 空间")
file(MAKE_DIRECTORY "${root}")
set(script "${WORK_DIR}/创建 场景.luau")
configure_file("${EXAMPLE}" "${script}" COPYONLY)
execute_process(COMMAND "${RUNNER}" --project-root "${root}" --script "${script}"
    RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 20 ENCODING UTF-8)
if(NOT code EQUAL 0 OR NOT output STREQUAL "" OR NOT errors STREQUAL "")
    message(FATAL_ERROR "Luau example exit=${code}; stderr=${errors}; stdout=${output}")
endif()
file(WRITE "${WORK_DIR}/reload.jsonl" [=[
{"jsonrpc":"2.0","id":1,"method":"scene.load","params":{"manifest":"project.json"}}
{"jsonrpc":"2.0","id":2,"method":"scene.query"}
]=])
execute_process(COMMAND "${RUNNER}" --project-root "${root}" --batch "${WORK_DIR}/reload.jsonl"
    RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 20 ENCODING UTF-8)
if(NOT code EQUAL 0 OR NOT errors STREQUAL "")
    message(FATAL_ERROR "Reload failed: ${code} ${errors} ${output}")
endif()
string(STRIP "${output}" output)
string(REPLACE "\n" ";" lines "${output}")
list(GET lines -1 query)
string(JSON count GET "${query}" result value state entity_count)
string(JSON dirty GET "${query}" result value state dirty)
if(NOT count EQUAL 3 OR dirty)
    message(FATAL_ERROR "Wrong persisted Luau scene: ${query}")
endif()
set(children 0)
foreach(index RANGE 0 2)
    string(JSON name GET "${query}" result value entities ${index} name)
    string(JSON x GET "${query}" result value entities ${index} world_matrix 3)
    if(name STREQUAL "实体 1")
        set(expected 2)
    elseif(name STREQUAL "实体 2")
        set(expected 6)
    elseif(name STREQUAL "实体 3")
        set(expected 8)
    else()
        message(FATAL_ERROR "Unexpected entity name: ${name}")
    endif()
    if(NOT x EQUAL expected)
        message(FATAL_ERROR "Persisted world transform differs for ${name}: ${x}")
    endif()
endforeach()

function(limited_case name source expected reason)
    set(case_root "${WORK_DIR}/limits/${name}")
    file(MAKE_DIRECTORY "${case_root}")
    file(WRITE "${case_root}/input.luau" "${source}")
    execute_process(COMMAND "${RUNNER}" --project-root "${case_root}" --script "${case_root}/input.luau" ${ARGN}
        RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 10 ENCODING UTF-8)
    if(NOT code EQUAL expected OR NOT output STREQUAL "")
        message(FATAL_ERROR "${name}: expected ${expected}, got ${code}; ${errors} ${output}")
    endif()
    if(NOT reason STREQUAL "" AND NOT errors MATCHES "${reason}")
        message(FATAL_ERROR "${name}: missing ${reason}: ${errors}")
    endif()
    if(expected EQUAL 0 AND NOT errors STREQUAL "")
        message(FATAL_ERROR "${name}: unexpected stderr: ${errors}")
    endif()
endfunction()
limited_case(timeout "while true do end" 2 "luau.timeout" --script-timeout-ms 20 --script-max-interrupts 1000000000)
limited_case(interrupt "while true do end" 2 "luau.interrupt_limit" --script-max-interrupts 20)
limited_case(commands "dk.command('commands.list'); dk.command('commands.list')" 2 "luau.command_limit" --script-max-commands 1)
limited_case(memory "pcall(function() table.create(1000000) end)" 2 "luau.memory_limit" --script-memory-mib 1)
limited_case(query "assert(dk.command('scene.new').error.name == 'not_supported'); assert(dk.command('commands.list').ok)" 0 "" --script-access query)
limited_case(edit "assert(dk.command('scene.new').ok); assert(dk.command('scene.save').error.name == 'not_supported')" 0 "" --script-access edit)
foreach(value IN ITEMS 0 -1 600001 2.5 nope 18446744073709551616)
    limited_case("invalid-time-${value}" "" 2 "Invalid arguments" --script-timeout-ms "${value}")
endforeach()
limited_case(invalid-memory "" 2 "Invalid arguments" --script-memory-mib 257)
limited_case(invalid-commands "" 2 "Invalid arguments" --script-max-commands 100001)
limited_case(invalid-interrupts "" 2 "Invalid arguments" --script-max-interrupts 1000000001)
limited_case(invalid-access "" 2 "Invalid arguments" --script-access everything)
limited_case(duplicate "" 2 "Invalid arguments" --script-timeout-ms 20 --script-timeout-ms 30)
string(REPEAT "a" 1048577 oversized)
limited_case(source "${oversized}" 2 "source exceeds byte limit")
execute_process(COMMAND "${RUNNER}" --project-root "${root}" --stdio --script-timeout-ms 20
    RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 10 ENCODING UTF-8)
if(NOT code EQUAL 2 OR NOT output STREQUAL "" OR errors STREQUAL "")
    message(FATAL_ERROR "Script limits accepted outside script mode")
endif()
foreach(case IN ITEMS syntax runtime extension missing mixed auto_guard)
    set(extra)
    set(bad "${WORK_DIR}/${case}.luau")
    file(WRITE "${bad}" "error('expected script failure')")
    if(case STREQUAL "syntax")
        file(WRITE "${bad}" "local =")
    elseif(case STREQUAL "extension")
        set(bad "${WORK_DIR}/external.bytecode")
        file(WRITE "${bad}" "not source")
    elseif(case STREQUAL "missing")
        set(bad "${WORK_DIR}/never-created.luau")
    elseif(case STREQUAL "mixed")
        list(APPEND extra --stdio)
    elseif(case STREQUAL "auto_guard")
        list(APPEND extra --auto-guard)
    endif()
    execute_process(COMMAND "${RUNNER}" --project-root "${root}" --script "${bad}" ${extra}
        RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 10 ENCODING UTF-8)
    if(NOT code EQUAL 2 OR NOT output STREQUAL "" OR errors STREQUAL "")
        message(FATAL_ERROR "${case}: expected error on stderr with exit 2: ${code} ${errors} ${output}")
    endif()
    if(case STREQUAL "runtime" AND NOT errors MATCHES "runtime.luau:1")
        message(FATAL_ERROR "Missing script location: ${errors}")
    endif()
endforeach()
