string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef run_id)
set(root "${WORK_DIR}/${run_id}/工程😀")
file(MAKE_DIRECTORY "${root}")
file(WRITE "${root}/mesh.bin" "Asset reference fixture; no mesh decoding in M2")
function(run_demo expected)
    execute_process(COMMAND "${DEMO}" ${ARGN} RESULT_VARIABLE result
        OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 20 ENCODING UTF-8)
    if(NOT result STREQUAL "${expected}")
        message(FATAL_ERROR "Expected ${expected}, got ${result}: ${error}")
    endif()
    if(NOT expected EQUAL 0 AND (NOT output STREQUAL "" OR error STREQUAL ""))
        message(FATAL_ERROR "Failure must use stderr only: ${output} / ${error}")
    endif()
    set(last_output "${output}" PARENT_SCOPE)
endfunction()
run_demo(0 create "${root}")
set(saved "${last_output}")
run_demo(0 load "${root}")
if(NOT saved STREQUAL last_output OR NOT saved MATCHES "entities=2" OR NOT saved MATCHES "dirty=0")
    message(FATAL_ERROR "Separate process reload changed scene identity or state")
endif()
file(SHA256 "${root}/scene.json" before)
file(RENAME "${root}/mesh.bin" "${root}/absent.bin")
run_demo(1 load "${root}")
file(SHA256 "${root}/scene.json" after)
if(NOT before STREQUAL after)
    message(FATAL_ERROR "Failed load modified scene file")
endif()
file(RENAME "${root}/absent.bin" "${root}/mesh.bin")
file(READ "${root}/scene.json" text)
string(REPLACE "\"version\": 1" "\"version\": 99" text "${text}")
file(WRITE "${root}/scene.json" "${text}")
run_demo(1 load "${root}")
run_demo(2)
file(GLOB temporary "${root}/.dk-save-*.tmp")
if(temporary)
    message(FATAL_ERROR "Temporary files remain: ${temporary}")
endif()
