# Windows app-local deployment must work without the developer's SDK/vcpkg PATH.
get_filename_component(bin "${SHADERC}" DIRECTORY)
get_filename_component(compiler_name "${SLANG}" NAME)
get_filename_component(optimizer_name "${OPTIMIZER}" NAME)
file(GLOB memory_dlls "${bin}/mimalloc*.dll")
file(GLOB modules "${bin}/slang-standard-module-*")
if(NOT memory_dlls OR NOT modules)
    message(FATAL_ERROR "Shader runtime deployment is incomplete")
endif()
string(RANDOM LENGTH 8 ALPHABET 0123456789abcdef run_id)
set(work "${WORK_DIR}/shaderc-deployment-${run_id}")
foreach(kind complete missing-optimizer)
    set(package "${work}/${kind}")
    file(MAKE_DIRECTORY "${package}")
    file(COPY "${SHADERC}" "${bin}/${compiler_name}" ${memory_dlls} ${modules}
        "${bin}/slang.slang" "${bin}/gfx.slang" DESTINATION "${package}")
    if(kind STREQUAL "complete")
        file(COPY "${bin}/${optimizer_name}" DESTINATION "${package}")
    endif()
    set(output "${package}/result.spv")
    file(WRITE "${output}" "previous-artifact")
    file(SHA256 "${output}" before)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env "PATH=$ENV{SystemRoot}/System32;$ENV{SystemRoot}" --
        "${package}/dk-shaderc.exe" compile --source "${SOURCE}" --entry computeMain --stage compute --output "${output}"
        WORKING_DIRECTORY "${package}" RESULT_VARIABLE code OUTPUT_VARIABLE json ERROR_VARIABLE diagnostics)
    if(kind STREQUAL "complete")
        if(NOT code EQUAL 0 OR NOT diagnostics STREQUAL "")
            message(FATAL_ERROR "Complete package failed or emitted unexpected diagnostics: ${code} / ${diagnostics}")
        endif()
        string(JSON compiler GET "${json}" compiler)
        if(compiler STREQUAL "")
            message(FATAL_ERROR "Missing compiler metadata")
        endif()
        file(READ "${output}" magic LIMIT 4 HEX)
        if(NOT magic STREQUAL "03022307")
            message(FATAL_ERROR "Complete package did not publish SPIR-V")
        endif()
    else()
        file(SHA256 "${output}" after)
        if(NOT code EQUAL 1 OR NOT json STREQUAL "" OR NOT diagnostics MATCHES "spirv-opt backend unavailable" OR NOT before STREQUAL after)
            message(FATAL_ERROR "Missing optimizer must fail without publishing: ${code} / ${json} / ${diagnostics}")
        endif()
    endif()
endforeach()
message(STATUS "Isolated app-local deployment and missing-optimizer failure verified")
