add_library(dk_scene_operations STATIC src/SceneOperations.cpp)
add_library(dk::scene_operations ALIAS dk_scene_operations)
target_sources(dk_scene_operations PUBLIC FILE_SET HEADERS BASE_DIRS include FILES include/dk/operations/SceneOperations.hpp)
target_link_libraries(dk_scene_operations PUBLIC dk::commands dk::scene_services)
dk_target_defaults(dk_scene_operations)
add_library(dk_simulation_operations STATIC src/SimulationOperations.cpp)
add_library(dk::simulation_operations ALIAS dk_simulation_operations)
target_sources(dk_simulation_operations PUBLIC FILE_SET HEADERS BASE_DIRS include FILES include/dk/operations/SimulationOperations.hpp)
target_link_libraries(dk_simulation_operations PUBLIC dk::commands dk::simulation_services PRIVATE dk::scene_operations)
dk_target_defaults(dk_simulation_operations)

if(TARGET dk_jobs)
    add_library(dk_job_operations STATIC src/JobOperations.cpp)
    add_library(dk::job_operations ALIAS dk_job_operations)
    target_sources(dk_job_operations PUBLIC FILE_SET HEADERS BASE_DIRS include FILES include/dk/operations/JobOperations.hpp)
    target_link_libraries(dk_job_operations PUBLIC dk::commands dk::jobs)
    dk_target_defaults(dk_job_operations)
endif()
if(TARGET dk_asset_services AND TARGET dk_jobs AND TARGET dk_asset_importers)
    add_library(dk_asset_operations STATIC src/AssetOperations.cpp)
    add_library(dk::asset_operations ALIAS dk_asset_operations)
    target_sources(dk_asset_operations PUBLIC FILE_SET HEADERS BASE_DIRS include FILES include/dk/operations/AssetOperations.hpp)
    target_link_libraries(dk_asset_operations PUBLIC dk::commands dk::asset_services PRIVATE dk::job_operations)
    dk_target_defaults(dk_asset_operations)
endif()

if(TARGET dk_render_services)
    add_library(dk_render_operations STATIC src/RenderOperations.cpp)
    add_library(dk::render_operations ALIAS dk_render_operations)
    target_sources(dk_render_operations PUBLIC FILE_SET HEADERS BASE_DIRS include FILES include/dk/operations/RenderOperations.hpp)
    target_link_libraries(dk_render_operations PUBLIC dk::commands dk::render_services PRIVATE dk::scene_operations)
    dk_target_defaults(dk_render_operations)
endif()
