add_library(dk_scene_operations STATIC src/SceneOperations.cpp)
add_library(dk::scene_operations ALIAS dk_scene_operations)
target_sources(dk_scene_operations PUBLIC FILE_SET HEADERS BASE_DIRS include FILES include/dk/operations/SceneOperations.hpp)
target_link_libraries(dk_scene_operations PUBLIC dk::commands dk::scene_services)
dk_target_defaults(dk_scene_operations)
if(TARGET dk_asset_services AND TARGET dk_jobs AND TARGET dk_asset_importers)
    add_library(dk_asset_operations STATIC src/AssetOperations.cpp)
    add_library(dk::asset_operations ALIAS dk_asset_operations)
    target_sources(dk_asset_operations PUBLIC FILE_SET HEADERS BASE_DIRS include FILES include/dk/operations/AssetOperations.hpp)
    target_link_libraries(dk_asset_operations PUBLIC dk::commands dk::asset_services)
    dk_target_defaults(dk_asset_operations)
endif()
