if(NOT DK_BUILD_MEMORY)
    message(FATAL_ERROR "DK_BUILD_GRAPHICS_DEVICE requires DK_BUILD_MEMORY")
endif()
find_package(VulkanHeaders CONFIG REQUIRED)
add_library(dk_graphics_device STATIC src/Device.cpp src/Selection.cpp)
add_library(dk::graphics_device ALIAS dk_graphics_device)
target_sources(dk_graphics_device PUBLIC FILE_SET HEADERS BASE_DIRS include FILES include/dk/graphics/Device.hpp)
target_link_libraries(dk_graphics_device PUBLIC dk::core dk::memory Vulkan::Headers PRIVATE dk::profiling ${CMAKE_DL_LIBS})
dk_target_defaults(dk_graphics_device)
