set(CMAKE_FOLDER "Engine/Graphics")
if(DK_BUILD_GRAPHICS_DEVICE OR DK_BUILD_GRAPHICS_SHADERS)
    add_subdirectory(shader-types)
endif()
if(DK_BUILD_GRAPHICS_DEVICE)
    add_subdirectory(device)
endif()
if(DK_BUILD_GRAPHICS_SHADERS)
    add_subdirectory(shaders)
endif()
if(DK_BUILD_GRAPHICS_OFFSCREEN)
    add_subdirectory(offscreen)
endif()
if(DK_BUILD_GRAPHICS_PRESENTATION)
    add_subdirectory(presentation)
endif()
