set(CMAKE_FOLDER "Engine/Scripting")
if(NOT TARGET dk_runtime)
    message(FATAL_ERROR "DK_BUILD_SCRIPTING_LUAU requires Framework/Scene Runtime")
endif()
find_package(unofficial-luau CONFIG REQUIRED)
add_library(dk_scripting_luau STATIC src/Luau.cpp)
add_library(dk::scripting_luau ALIAS dk_scripting_luau)
target_sources(dk_scripting_luau PUBLIC FILE_SET HEADERS BASE_DIRS include FILES include/dk/scripting/Luau.hpp)
target_link_libraries(dk_scripting_luau PUBLIC dk::runtime PRIVATE unofficial::luau::Luau.Compiler unofficial::luau::Luau.VM)
dk_target_defaults(dk_scripting_luau)
