file(GLOB modules "${SOURCE_DIR}/slang-standard-module-*")
if(NOT modules)
    message(FATAL_ERROR "Slang standard modules missing beside ${SOURCE_DIR}")
endif()
foreach(module IN LISTS modules)
    file(COPY "${module}" DESTINATION "${DESTINATION_DIR}")
endforeach()
foreach(binding slang.slang gfx.slang)
    if(NOT EXISTS "${SOURCE_DIR}/${binding}")
        message(FATAL_ERROR "Slang API binding missing: ${SOURCE_DIR}/${binding}")
    endif()
    file(COPY "${SOURCE_DIR}/${binding}" DESTINATION "${DESTINATION_DIR}")
endforeach()
