add_library(dk_automation_transport STATIC src/NamedPipe.cpp)
add_library(dk::automation_transport ALIAS dk_automation_transport)
target_sources(dk_automation_transport PUBLIC FILE_SET HEADERS BASE_DIRS include FILES include/dk/automation/NamedPipe.hpp)
target_link_libraries(dk_automation_transport PUBLIC dk::core)
find_package(Threads REQUIRED)
target_link_libraries(dk_automation_transport PRIVATE Threads::Threads Advapi32)
dk_target_defaults(dk_automation_transport)
